name: janusgraph-app
serviceType: playground

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: docker.io
  name: janusgraph/janusgraph
  tag: 1.0.0-rc2
  pullPolicy: IfNotPresent
